/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import googleMaps from "@amicaldo/strapi-google-maps/strapi-admin";
import strapiCloud from "@strapi/plugin-cloud/strapi-admin";
import colorPicker from "@strapi/plugin-color-picker/strapi-admin";
import i18N from "@strapi/plugin-i18n/strapi-admin";
import seo from "@strapi/plugin-seo/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import navigation from "strapi-plugin-navigation/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

import customisations from "../../src/admin/app.js";

renderAdmin(document.getElementById("strapi"), {
  customisations,

  plugins: {
    "google-maps": googleMaps,
    "strapi-cloud": strapiCloud,
    "color-picker": colorPicker,
    i18n: i18N,
    seo: seo,
    "users-permissions": usersPermissions,
    navigation: navigation,
  },
});
